### ISSUE TITLE
不要な空行

### ISSUE THREAD

**Issue by c0b21145** [a123ktx/ProjExD#1]
https://github.com/a123ktx/ProjExD/blob/7d2654951962b9cb6a5d36d74a814db0a3e648cc/ex01/game.py#L43

空行が多く続いているので消した方が良いと思います。

**Comment by a123ktx** [comment]
空行すると見やすくなるかと思いましたが逆効果でした。アドバイスありがとうございます

**Comment by a123ktx** [comment]
違った、ただの消し忘れでした。お恥ずかしい
