### ISSUE TITLE
グローバル変数名

### ISSUE THREAD

**Issue by c0b210990e** [a123ktx/ProjExD#2]
https://github.com/a123ktx/ProjExD/blob/7d2654951962b9cb6a5d36d74a814db0a3e648cc/ex01/game.py#L3

グローバル変数名を"kesson"など具体的にするとわかりやすくなると思いました

**Comment by a123ktx** [comment]
確かに明日以降見る時、なんもわかんない状態になりそうですね。アドバイスありがとうございます
