### ISSUE TITLE
空行

### ISSUE THREAD

**Issue by c0b21043** [a123ktx/ProjExD#9]
https://github.com/a123ktx/ProjExD/blob/fa897729c6622da0a1410c0e2e5e25ef91ea725b/ex05/fight_kokaton.py#L124
124~125を1行空け、128~131を2行空けにするとさらにいい感じになると思いました。あとそれぞれのコメントが分かりやすくてとても良いです。

**Comment by a123ktx** [comment]
空行癖が無限に治らない、指摘ありがとう
